// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250213221433_CreateCommitmentTable")]
    partial class CreateCommitmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Backend.Models.Investor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommitmentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentAssetClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorCountry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvestorDateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvestorLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Investors");
                });
#pragma warning restore 612, 618
        }
    }
}
